In [2]:
import numpy as np

In [4]:
arreglo_grados = np.array([0,30,55,60,90])

In [7]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.95993109, 1.04719755, 1.57079633])

In [9]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.81915204, 0.8660254 , 1.        ])

In [11]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 5.73576436e-01, 5.00000000e-01,
       6.12323400e-17])

In [12]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.42814801e+00, 1.73205081e+00,
       1.63312394e+16])

In [45]:
arreglo_random = np.random.randint(11) # [0, 11[
arreglo_random

7

In [56]:
numero_random_negativo = np.random.randint(-9,2)
numero_random_negativo

-1

In [60]:
arreglo_random = np.random.randint(
    10,
    20,
    8
)
arreglo_random

array([16, 11, 14, 15, 15, 13, 12, 19])

In [63]:
np.random.rand(9)
np.random.rand(3,2) # EN este caso si no son limites son dimensiones para que sean llimites deverian ser 2,3

array([[0.34878128, 0.89632678],
       [0.75113594, 0.65623763],
       [0.82452428, 0.25064624]])

In [65]:
np.average(arreglo_random)

14.375

In [66]:
np.mean(arreglo_random)

14.375

In [68]:
np.median(arreglo_random)

14.5

In [70]:
np.std(arreglo_random)

2.341874249399399

In [72]:
np.var(arreglo_random)

5.484375

In [73]:
arreglo_random.mean()

14.375